// <auto-generated />
using System;
using BookApplication1.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookApplication1.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118041232_AddProductTableAndSeedData")]
    partial class AddProductTableAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookApplication1.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Thiller"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Sci-fi"
                        });
                });

            modelBuilder.Entity("BookApplication1.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EditionNum")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "A. Reynolds",
                            CreatedAt = new DateOnly(2023, 5, 1),
                            Date = new DateOnly(2023, 5, 12),
                            Description = "A thrilling sci-fi adventure across space and time.",
                            EditionNum = 2,
                            ISBN = "978-1-23456-789-7",
                            Name = "The Time Traveler",
                            Price = 499.99f,
                            Quantity = 50,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2023, 5, 12)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Sarah Blake",
                            CreatedAt = new DateOnly(2022, 11, 1),
                            Date = new DateOnly(2022, 11, 20),
                            Description = "A gripping thriller filled with suspense and twists.",
                            EditionNum = 1,
                            ISBN = "978-1-98765-432-1",
                            Name = "Mystery of the Lost Manor",
                            Price = 299.5f,
                            Quantity = 80,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2022, 11, 20)
                        },
                        new
                        {
                            Id = 3,
                            Author = "James Carter",
                            CreatedAt = new DateOnly(2024, 1, 1),
                            Date = new DateOnly(2024, 1, 10),
                            Description = "An epic sci-fi saga exploring distant galaxies.",
                            EditionNum = 3,
                            ISBN = "978-0-12345-678-9",
                            Name = "Galactic Frontiers",
                            Price = 599f,
                            Quantity = 40,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2024, 1, 10)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
