// <auto-generated />
using System;
using BookApplication1.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookApplication1.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121053557_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookApplication1.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Sci-fi"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "History"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Self-Help"
                        });
                });

            modelBuilder.Entity("BookApplication1.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EditionNum")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateOnly>("PublishedDate")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "A. Reynolds",
                            CategoryId = 3,
                            CreatedAt = new DateOnly(2023, 5, 1),
                            Description = "A thrilling sci-fi adventure across space and time.",
                            EditionNum = 2,
                            ISBN = "978-1-23456-789-7",
                            ImageURL = "",
                            Name = "The Time Traveler",
                            Price = 499.99f,
                            PublishedDate = new DateOnly(2023, 5, 12),
                            Quantity = 50,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2023, 5, 12)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Sarah Blake",
                            CategoryId = 2,
                            CreatedAt = new DateOnly(2022, 11, 1),
                            Description = "A gripping thriller filled with suspense and twists.",
                            EditionNum = 1,
                            ISBN = "978-1-98765-432-1",
                            ImageURL = "",
                            Name = "Mystery of the Lost Manor",
                            Price = 299.5f,
                            PublishedDate = new DateOnly(2022, 11, 20),
                            Quantity = 80,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2022, 11, 20)
                        },
                        new
                        {
                            Id = 3,
                            Author = "James Carter",
                            CategoryId = 3,
                            CreatedAt = new DateOnly(2024, 1, 1),
                            Description = "An epic sci-fi saga exploring distant galaxies.",
                            EditionNum = 3,
                            ISBN = "978-0-12345-678-9",
                            ImageURL = "",
                            Name = "Galactic Frontiers",
                            Price = 599f,
                            PublishedDate = new DateOnly(2024, 1, 10),
                            Quantity = 40,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2024, 1, 10)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Evelyn Hart",
                            CategoryId = 4,
                            CreatedAt = new DateOnly(2021, 8, 1),
                            Description = "A dark fantasy adventure blending magic, mythology, and mystery.",
                            EditionNum = 1,
                            ISBN = "978-1-54321-987-6",
                            ImageURL = "",
                            Name = "Shadows of the Forgotten Realm",
                            Price = 450f,
                            PublishedDate = new DateOnly(2021, 8, 17),
                            Quantity = 120,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2021, 8, 17)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Dr. Neil Harmon",
                            CategoryId = 3,
                            CreatedAt = new DateOnly(2023, 3, 1),
                            Description = "A mind-bending story about alternate timelines and cosmic secrets.",
                            EditionNum = 2,
                            ISBN = "978-0-24680-135-7",
                            ImageURL = "",
                            Name = "The Quantum Paradox",
                            Price = 650f,
                            PublishedDate = new DateOnly(2023, 3, 2),
                            Quantity = 35,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2023, 3, 2)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Kenji Morita",
                            CategoryId = 1,
                            CreatedAt = new DateOnly(2020, 12, 1),
                            Description = "A samurai-inspired action novel full of honor, conflict, and redemption.",
                            EditionNum = 3,
                            ISBN = "978-1-67890-555-3",
                            ImageURL = "",
                            Name = "Echoes of the Crimson Blade",
                            Price = 520.5f,
                            PublishedDate = new DateOnly(2020, 12, 5),
                            Quantity = 60,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2020, 12, 5)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Maya Collins",
                            CategoryId = 2,
                            CreatedAt = new DateOnly(2022, 4, 1),
                            Description = "A slow-burn mystery unraveling eerie clues in a quiet lakeside town.",
                            EditionNum = 1,
                            ISBN = "978-0-11223-445-8",
                            ImageURL = "",
                            Name = "Beneath the Silver Lake",
                            Price = 310f,
                            PublishedDate = new DateOnly(2022, 4, 14),
                            Quantity = 95,
                            Rating = 3,
                            UpdatedAt = new DateOnly(2022, 4, 14)
                        },
                        new
                        {
                            Id = 8,
                            Author = "L. Vargas",
                            CategoryId = 3,
                            CreatedAt = new DateOnly(2024, 2, 1),
                            Description = "A futuristic action thriller set in a war-torn cyberpunk world.",
                            EditionNum = 2,
                            ISBN = "978-9-87654-320-4",
                            ImageURL = "",
                            Name = "Rise of the Cyber Dominion",
                            Price = 799f,
                            PublishedDate = new DateOnly(2024, 2, 1),
                            Quantity = 20,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2024, 2, 1)
                        },
                        new
                        {
                            Id = 9,
                            Author = "Isabella Grant",
                            CategoryId = 7,
                            CreatedAt = new DateOnly(2023, 7, 1),
                            Description = "A historical mystery following the hunt for a forbidden ancient manuscript.",
                            EditionNum = 1,
                            ISBN = "978-1-22468-975-3",
                            ImageURL = "",
                            Name = "The Alchemist’s Secret Grimoire",
                            Price = 560.75f,
                            PublishedDate = new DateOnly(2023, 7, 22),
                            Quantity = 70,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2023, 7, 22)
                        },
                        new
                        {
                            Id = 10,
                            Author = "Theo Marquez",
                            CategoryId = 3,
                            CreatedAt = new DateOnly(2021, 9, 1),
                            Description = "A philosophical sci-fi novel exploring the human condition through space travel.",
                            EditionNum = 4,
                            ISBN = "978-1-30987-642-2",
                            ImageURL = "",
                            Name = "Voyage to the Edge of Nowhere",
                            Price = 480f,
                            PublishedDate = new DateOnly(2021, 9, 29),
                            Quantity = 55,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2021, 9, 29)
                        },
                        new
                        {
                            Id = 11,
                            Author = "Jordan Pierce",
                            CategoryId = 2,
                            CreatedAt = new DateOnly(2022, 2, 1),
                            Description = "A chilling psychological thriller set in an abandoned hospital.",
                            EditionNum = 1,
                            ISBN = "978-0-33445-221-7",
                            ImageURL = "",
                            Name = "The Silent Ward",
                            Price = 350f,
                            PublishedDate = new DateOnly(2022, 2, 10),
                            Quantity = 110,
                            Rating = 3,
                            UpdatedAt = new DateOnly(2022, 2, 10)
                        },
                        new
                        {
                            Id = 12,
                            Author = "Ariana Vale",
                            CategoryId = 4,
                            CreatedAt = new DateOnly(2023, 10, 1),
                            Description = "An epic fantasy journey through a fallen kingdom full of secrets.",
                            EditionNum = 2,
                            ISBN = "978-1-44444-222-9",
                            ImageURL = "",
                            Name = "Chronicles of the Forgotten Empire",
                            Price = 899f,
                            PublishedDate = new DateOnly(2023, 10, 4),
                            Quantity = 25,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2023, 10, 4)
                        },
                        new
                        {
                            Id = 13,
                            Author = "Cyrus Lee",
                            CategoryId = 3,
                            CreatedAt = new DateOnly(2024, 3, 1),
                            Description = "A cyber-noir story exploring technology, identity, and rebellion.",
                            EditionNum = 1,
                            ISBN = "978-2-54321-111-6",
                            ImageURL = "",
                            Name = "Fragments of the Neon Sky",
                            Price = 420f,
                            PublishedDate = new DateOnly(2024, 3, 12),
                            Quantity = 75,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2024, 3, 12)
                        },
                        new
                        {
                            Id = 14,
                            Author = "Adrian Wells",
                            CategoryId = 2,
                            CreatedAt = new DateOnly(2025, 11, 21),
                            Description = "A psychological thriller exploring the human mind.",
                            EditionNum = 1,
                            ISBN = "978-1-54321-765-4-2",
                            ImageURL = "",
                            Name = "The Silent Observer",
                            Price = 499f,
                            PublishedDate = new DateOnly(2018, 5, 12),
                            Quantity = 0,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2025, 11, 21)
                        },
                        new
                        {
                            Id = 15,
                            Author = "Laura Kim",
                            CategoryId = 5,
                            CreatedAt = new DateOnly(2025, 11, 21),
                            Description = "A complete guide to mastering full-stack web frameworks and tools.",
                            EditionNum = 2,
                            ISBN = "978-1-98765-123-6-1",
                            ImageURL = "",
                            Name = "Modern Web Development",
                            Price = 899f,
                            PublishedDate = new DateOnly(2021, 3, 1),
                            Quantity = 0,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2025, 11, 21)
                        },
                        new
                        {
                            Id = 16,
                            Author = "Caleb Morgan",
                            CategoryId = 6,
                            CreatedAt = new DateOnly(2025, 11, 21),
                            Description = "A journey into marine mysteries and ocean life.",
                            EditionNum = 1,
                            ISBN = "978-1-33445-667-8-9",
                            ImageURL = "",
                            Name = "Into the Deep Blue",
                            Price = 350f,
                            PublishedDate = new DateOnly(2015, 11, 20),
                            Quantity = 0,
                            Rating = 3,
                            UpdatedAt = new DateOnly(2025, 11, 21)
                        },
                        new
                        {
                            Id = 17,
                            Author = "Meera Patel",
                            CategoryId = 5,
                            CreatedAt = new DateOnly(2025, 11, 21),
                            Description = "Understanding artificial intelligence in everyday life.",
                            EditionNum = 1,
                            ISBN = "978-1-22334-998-7-6",
                            ImageURL = "",
                            Name = "AI for Everyone",
                            Price = 750f,
                            PublishedDate = new DateOnly(2022, 7, 10),
                            Quantity = 0,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2025, 11, 21)
                        },
                        new
                        {
                            Id = 18,
                            Author = "Rohan Khanna",
                            CategoryId = 4,
                            CreatedAt = new DateOnly(2025, 11, 21),
                            Description = "A collection of ancient stories retold for modern readers.",
                            EditionNum = 3,
                            ISBN = "978-1-55678-224-3-4",
                            ImageURL = "",
                            Name = "The Forgotten Tales",
                            Price = 420f,
                            PublishedDate = new DateOnly(2010, 1, 5),
                            Quantity = 0,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2025, 11, 21)
                        },
                        new
                        {
                            Id = 19,
                            Author = "Sofia Bennett",
                            CategoryId = 8,
                            CreatedAt = new DateOnly(2025, 11, 21),
                            Description = "Easy and delicious recipes for everyday cooking.",
                            EditionNum = 1,
                            ISBN = "978-1-44223-556-5-3",
                            ImageURL = "",
                            Name = "Cooking with Passion",
                            Price = 650f,
                            PublishedDate = new DateOnly(2019, 8, 18),
                            Quantity = 0,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2025, 11, 21)
                        },
                        new
                        {
                            Id = 20,
                            Author = "Neil Carver",
                            CategoryId = 3,
                            CreatedAt = new DateOnly(2025, 11, 21),
                            Description = "A sci-fi adventure exploring distant galaxies.",
                            EditionNum = 2,
                            ISBN = "978-1-99887-332-1-8",
                            ImageURL = "",
                            Name = "The Stars Beyond",
                            Price = 580f,
                            PublishedDate = new DateOnly(2017, 6, 9),
                            Quantity = 0,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2025, 11, 21)
                        },
                        new
                        {
                            Id = 21,
                            Author = "James Holloway",
                            CategoryId = 5,
                            CreatedAt = new DateOnly(2025, 11, 21),
                            Description = "A deep dive into backend development with C# and .NET Core.",
                            EditionNum = 1,
                            ISBN = "978-1-11223-456-7-4",
                            ImageURL = "",
                            Name = "Mastering C# and .NET",
                            Price = 999f,
                            PublishedDate = new DateOnly(2023, 2, 15),
                            Quantity = 0,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2025, 11, 21)
                        },
                        new
                        {
                            Id = 22,
                            Author = "Elena Rivers",
                            CategoryId = 9,
                            CreatedAt = new DateOnly(2025, 11, 21),
                            Description = "How minimalism transforms lifestyle, productivity, and mindset.",
                            EditionNum = 1,
                            ISBN = "978-1-77889-554-3-7",
                            ImageURL = "",
                            Name = "The Art of Minimalism",
                            Price = 320f,
                            PublishedDate = new DateOnly(2016, 9, 27),
                            Quantity = 0,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2025, 11, 21)
                        },
                        new
                        {
                            Id = 23,
                            Author = "Dr. Nathan Clarke",
                            CategoryId = 7,
                            CreatedAt = new DateOnly(2025, 11, 21),
                            Description = "From Mesopotamia to Rome – a detailed historical exploration.",
                            EditionNum = 2,
                            ISBN = "978-1-66554-778-2-9",
                            ImageURL = "",
                            Name = "History of Ancient Civilizations",
                            Price = 850f,
                            PublishedDate = new DateOnly(2012, 4, 30),
                            Quantity = 0,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2025, 11, 21)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookApplication1.Models.Models.Product", b =>
                {
                    b.HasOne("BookApplication1.Models.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
