// <auto-generated />
using System;
using BookApplication1.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookApplication1.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118051307_SeedMoreProducts")]
    partial class SeedMoreProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookApplication1.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Thiller"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Sci-fi"
                        });
                });

            modelBuilder.Entity("BookApplication1.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EditionNum")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "A. Reynolds",
                            CreatedAt = new DateOnly(2023, 5, 1),
                            Date = new DateOnly(2023, 5, 12),
                            Description = "A thrilling sci-fi adventure across space and time.",
                            EditionNum = 2,
                            ISBN = "978-1-23456-789-7",
                            Name = "The Time Traveler",
                            Price = 499.99f,
                            Quantity = 50,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2023, 5, 12)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Sarah Blake",
                            CreatedAt = new DateOnly(2022, 11, 1),
                            Date = new DateOnly(2022, 11, 20),
                            Description = "A gripping thriller filled with suspense and twists.",
                            EditionNum = 1,
                            ISBN = "978-1-98765-432-1",
                            Name = "Mystery of the Lost Manor",
                            Price = 299.5f,
                            Quantity = 80,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2022, 11, 20)
                        },
                        new
                        {
                            Id = 3,
                            Author = "James Carter",
                            CreatedAt = new DateOnly(2024, 1, 1),
                            Date = new DateOnly(2024, 1, 10),
                            Description = "An epic sci-fi saga exploring distant galaxies.",
                            EditionNum = 3,
                            ISBN = "978-0-12345-678-9",
                            Name = "Galactic Frontiers",
                            Price = 599f,
                            Quantity = 40,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2024, 1, 10)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Evelyn Hart",
                            CreatedAt = new DateOnly(2021, 8, 1),
                            Date = new DateOnly(2021, 8, 17),
                            Description = "A dark fantasy adventure blending magic, mythology, and mystery.",
                            EditionNum = 1,
                            ISBN = "978-1-54321-987-6",
                            Name = "Shadows of the Forgotten Realm",
                            Price = 450f,
                            Quantity = 120,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2021, 8, 17)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Dr. Neil Harmon",
                            CreatedAt = new DateOnly(2023, 3, 1),
                            Date = new DateOnly(2023, 3, 2),
                            Description = "A mind-bending story about alternate timelines and cosmic secrets.",
                            EditionNum = 2,
                            ISBN = "978-0-24680-135-7",
                            Name = "The Quantum Paradox",
                            Price = 650f,
                            Quantity = 35,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2023, 3, 2)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Kenji Morita",
                            CreatedAt = new DateOnly(2020, 12, 1),
                            Date = new DateOnly(2020, 12, 5),
                            Description = "A samurai-inspired action novel full of honor, conflict, and redemption.",
                            EditionNum = 3,
                            ISBN = "978-1-67890-555-3",
                            Name = "Echoes of the Crimson Blade",
                            Price = 520.5f,
                            Quantity = 60,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2020, 12, 5)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Maya Collins",
                            CreatedAt = new DateOnly(2022, 4, 1),
                            Date = new DateOnly(2022, 4, 14),
                            Description = "A slow-burn mystery unraveling eerie clues in a quiet lakeside town.",
                            EditionNum = 1,
                            ISBN = "978-0-11223-445-8",
                            Name = "Beneath the Silver Lake",
                            Price = 310f,
                            Quantity = 95,
                            Rating = 3,
                            UpdatedAt = new DateOnly(2022, 4, 14)
                        },
                        new
                        {
                            Id = 8,
                            Author = "L. Vargas",
                            CreatedAt = new DateOnly(2024, 2, 1),
                            Date = new DateOnly(2024, 2, 1),
                            Description = "A futuristic action thriller set in a war-torn cyberpunk world.",
                            EditionNum = 2,
                            ISBN = "978-9-87654-320-4",
                            Name = "Rise of the Cyber Dominion",
                            Price = 799f,
                            Quantity = 20,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2024, 2, 1)
                        },
                        new
                        {
                            Id = 9,
                            Author = "Isabella Grant",
                            CreatedAt = new DateOnly(2023, 7, 1),
                            Date = new DateOnly(2023, 7, 22),
                            Description = "A historical mystery following the hunt for a forbidden ancient manuscript.",
                            EditionNum = 1,
                            ISBN = "978-1-22468-975-3",
                            Name = "The Alchemist’s Secret Grimoire",
                            Price = 560.75f,
                            Quantity = 70,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2023, 7, 22)
                        },
                        new
                        {
                            Id = 10,
                            Author = "Theo Marquez",
                            CreatedAt = new DateOnly(2021, 9, 1),
                            Date = new DateOnly(2021, 9, 29),
                            Description = "A philosophical sci-fi novel exploring the human condition through space travel.",
                            EditionNum = 4,
                            ISBN = "978-1-30987-642-2",
                            Name = "Voyage to the Edge of Nowhere",
                            Price = 480f,
                            Quantity = 55,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2021, 9, 29)
                        },
                        new
                        {
                            Id = 11,
                            Author = "Jordan Pierce",
                            CreatedAt = new DateOnly(2022, 2, 1),
                            Date = new DateOnly(2022, 2, 10),
                            Description = "A chilling psychological thriller set in an abandoned hospital.",
                            EditionNum = 1,
                            ISBN = "978-0-33445-221-7",
                            Name = "The Silent Ward",
                            Price = 350f,
                            Quantity = 110,
                            Rating = 3,
                            UpdatedAt = new DateOnly(2022, 2, 10)
                        },
                        new
                        {
                            Id = 12,
                            Author = "Ariana Vale",
                            CreatedAt = new DateOnly(2023, 10, 1),
                            Date = new DateOnly(2023, 10, 4),
                            Description = "An epic fantasy journey through a fallen kingdom full of secrets.",
                            EditionNum = 2,
                            ISBN = "978-1-44444-222-9",
                            Name = "Chronicles of the Forgotten Empire",
                            Price = 899f,
                            Quantity = 25,
                            Rating = 5,
                            UpdatedAt = new DateOnly(2023, 10, 4)
                        },
                        new
                        {
                            Id = 13,
                            Author = "Cyrus Lee",
                            CreatedAt = new DateOnly(2024, 3, 1),
                            Date = new DateOnly(2024, 3, 12),
                            Description = "A cyber-noir story exploring technology, identity, and rebellion.",
                            EditionNum = 1,
                            ISBN = "978-2-54321-111-6",
                            Name = "Fragments of the Neon Sky",
                            Price = 420f,
                            Quantity = 75,
                            Rating = 4,
                            UpdatedAt = new DateOnly(2024, 3, 12)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
